shared:
  # Rules applicable to both queueing and merge requests.
  compulsory: &compulsory

    # Ensure the minimal CI checks have passed.
    - check-success=DCO
    - check-success=Build (amd64, archive2disk)
    - check-success=Build (amd64, cexec)
    - check-success=Build (amd64, grub2disk)
    - check-success=Build (amd64, image2disk)
    - check-success=Build (amd64, kexec)
    - check-success=Build (amd64, oci2disk)
    - check-success=Build (amd64, qemuimg2disk)
    - check-success=Build (amd64, rootio)
    - check-success=Build (amd64, slurp)
    - check-success=Build (amd64, syslinux)
    - check-success=Build (amd64, writefile)

    # Ensure we're targetting the default branch.
    - base=main

    # Ensure we have adequete reviews.
    - "#approved-reviews-by>=1"
    - "#changes-requested-reviews-by=0"

    # Ensure we aren't being explicitly blocked with a label.
    - label!=do-not-merge

queue_rules:
  - name: default
    queue_conditions:
      - and: *compulsory
      - label=ready-to-merge
    merge_conditions:
      - and: *compulsory

    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: merge

pull_request_rules:
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
